version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(levelname)s:   %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO

  fastapi:
    level: INFO

root:
  level: ERROR
  handlers: [console]